### ISSUE TITLE
Aggregated Type not updating for Chart Type

### ISSUE THREAD

**Issue by jutklos** [krmorse/CustomChart#3]
I am attempting to create a Feature throughput chart using this app with Aggregated Type = Preliminary Estimate and my only options are 'Count' and 'Plan Est.' for Aggregated Type. I understand Count here but Plan est is a User Story attribute and I guess I would have assumed that when I selected Chart Type = Feature that I would have been able to use prelim est instead. Am I in right field with this assumption?

**Comment by krmorse** [comment]
Fixed!
